swagger: '2.0'
info:
  title: rit-test
  x-ibm-name: rit-test
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - map:
          version: 2.0.0
          title: map
          inputs: {}
          outputs:
            response:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    name: id
                  value:
                    type: string
                    name: value
              variable: message.body
              content: application/json
          actions: []
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
  servers:
    - url: https://apis-minimum-gw-gateway-cp4i.itzroks-5500001s8k-h1etpb-6ccd7f378ae819553d37d5f2ee142bd6-0000.eu-gb.containers.appdomain.cloud/dev/sandbox/rit-test
      description: ''
      type:
        - production
        - development
  oauth-servers: []
basePath: /rit-test
paths:
  /rit-test:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces:
        - application/json
      security:
        - clientID: []
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      operationId: POST
      produces:
        - application/json
      consumes:
        - application/json
      security:
        - clientID: []
      schemes: []
      parameters: []
    parameters: []
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientID: []
schemes:
  - https
definitions: {}
parameters: {}
swagger: '2.0'
info:
  version: 1.0.0
  title: test api
  x-ibm-name: test-api
basePath: /test-api
x-ibm-configuration:
  properties:
    target-url:
      value: https://httpbin.org/get
      description: URL of the proxy policy
      encoded: false
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - invoke:
          title: invoke
          version: 2.0.0
          verb: keep
          target-url: $(target-url)
          follow-redirects: false
          timeout: 60
          parameter-control:
            type: blocklist
            values: []
          header-control:
            type: blocklist
            values: []
          inject-proxy-headers: true
  servers:
    - url: https://apis-minimum-gw-gateway-cp4i.itzroks-5500001s8k-h1etpb-6ccd7f378ae819553d37d5f2ee142bd6-0000.eu-gb.containers.appdomain.cloud/dev/sandbox/httpbin.org/test-api
      description: ''
      type:
        - production
        - development
  oauth-servers: []
paths:
  /get:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientID: ["cbfe81a0948d4b6f47537d6eedaaaf8a"]
schemes:
  - https
host: httpbin.org
definitions: {}

